global using Microsoft.AspNetCore.Http;
global using System.ComponentModel.DataAnnotations;
global using Movies.Services.Attributes;
global using Movies.Services.Settings;
global using Movies.Core.Models;
global using Movies.Services.DTOs.Generes;
global using Movies.Services.DTOs.Movies;
global using AutoMapper;
global using Movies.Core.Interfaces;
